### ISSUE TITLE
ODE Mass problem.

### ISSUE THREAD

**Issue by OzgurEraslan** [RoboCup-SSL/grSim#13]
I got this error, then I run grsim in bin folder.

XML Parsing error inside file '/home/ozgur/.grsim.xml'.
Error: File not found
At line 0, column 0.

ODE Message 2: mass must be > 0 in dMassCheck() File mass.cpp Line 49

ODE Message 2: mass must be > 0 in dMassCheck() File mass.cpp Line 49

ODE INTERNAL ERROR 1: assertion "dMassCheck(mass)" failed in dBodySetMass() [ode.cpp]
Aborted (core dumped)

**Comment by jgkamat** [comment]
I just ran into this as well. I think this should be noted on the README, and perhaps support for non-double precision should be added as well. You can't guarentee that all packaged ODE's have that flag on.

**Comment by mahi97** [comment]
thanks for your comment
It's mentioned inside INSTALL.md file, but support for single precision is needed though.
is there any problem for you to install ODE with double precision ?

**Comment by jgkamat** [comment]
Oh, I didn't see the note in INSTALL, thats my bad! I just skimmed the install requirements and assumed there was a bug somewhere.

I use gentoo, so it's easy for me to add the double flag, but for others (running ubuntu or other distros, with packaged ODE's) they would have to manually install ODE which is undesirable. Ideally grsim would support both (but perform better with double precsion).

**Comment by Anamaria11** [comment]
Hello,
I got this error, then I run grsim in bin folder.
ana@anamaria11:~/grSim/bin$ ./grsim

ODE Message 2: mass must be > 0 in dMassCheck() [mass.cpp:49]

ODE Message 2: mass must be > 0 in dMassCheck() [mass.cpp:49]

ODE INTERNAL ERROR 1: assertion "dMassCheck(mass)" failed in dBodySetMass() [ode.cpp:485]
Abortado (`core' generado)
Please help me

**Comment by jgkamat** [comment]
@Anamaria11 how did you install ODE? You will need to make sure you have the `DOUBLE` option enabled when ODE is built. It looks like this can be done by passing `--enable-double-precision` to configure. You can check [this webpage for more information on building ODE](https://www.ode-wiki.org/wiki/index.php?title=Manual:_Install_and_Use)

**Comment by edgarcamilocamacho** [comment]
(Ubuntu 18.04 LTS and 16.04 LTS) I compiled and installed ODE with the "--enable-double-precision" flag but I got the same error, then, I tried to apply the @Anamaria11 's solution (installing vartypes 0.7) but I couldn't because of problems with c++11, but I found that, if I close grSim, open ~/.grsim.xml and change all the dots by commas (except by "﻿<?xml version="1.0" encoding="utf-8"?>" and "<VarString name="Vision multicast address"> 224.5.23.2 </VarString>"), it works. But I have to do that every time I want to open grSim.

**Comment by edgarcamilocamacho** [comment]
It seems that the problem is like this:
https://stackoverflow.com/questions/13489940/stupid-bug-with-fscanf-comma-instead-of-point
I solved the problem setting the following environment variables before executing grsim:
$ export LANG=en_US.UTF-8
$ export LC_CTYPE=en_US.UTF-8
$ export LC_ALL=en_US.UTF-8

**Comment by jgkamat** [comment]
@edgarcamilocamacho if you are on ubuntu, I'm fairly certain that the [libode-dev](https://packages.debian.org/stretch/libode-dev) package has double precision enabled, and you won't need to compile anything. 

The error you have linked seems like a different issue, maybe a warning should be printed if the current locale dosen't support UTF.

**Comment by CoAuToSe** [comment]
When I have this problem, which appeared after a relaunch of my computer, I delete `~/.grsim.xml` and relaunch grSim with `cd grSim && ./bin/grSim` and it seems to resolve the problem. So it seems that the file `.grsim.xml` get corrupted after a restart or something alike.
